Algoritmo "MEDIA_DA_IDADE"
Var
nome1, nome2: caractere
idade1, idade2, med: real
Inicio
Escreval("-------------------------------------------")
Escreval("             Seja Bem Vindo!!              ")
Escreval("-------------------------------------------")
Escreval("Digite um nome: ")
Leia(nome1)
Escreval("Digite a idade: ")
Leia(idade1)
Escreval("Digite outro nome: ")
Leia(nome2)
Escreval("Digite a idade: ")
Leia(idade2)
//----------------------------------------------
med<-(idade1+idade2)/2
Escreval("-------------------------------------------")
Escreval("A idade media de ", nome1, " e ", nome2, " é de ", med:5:1, " anos.")
Escreval("-------------------------------------------")

Fimalgoritmo