Algoritmo "teste_saida"
Var
produto1, produto2, genero: caractere
preco1, preco2: real
idade, codigo: inteiro


inicio
produto1<-"Computador"
produto2<-"TV"
preco1<-2100.5
preco2<-1830.0
idade<-30
codigo<-5391
genero<-"F"

escreval("Produtos: ")
escreval("O produto ", produto1, " custa R$", preco1:10:2)
escreval("O produto ", produto2, " custa R$", preco2:10:2)
escreval("Codigo = ", codigo)
escreval("Dados da pessoa: genero ", genero, " e idade", idade)


Fimalgoritmo